# Generated by Django 3.2.18 on 2023-05-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_faculty_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='icon',
        ),
    ]
